version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive --acl public-read ./build s3://movie-fuel-website-production/
      - aws s3 cp --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./build/index.html s3://movie-fuel-website-production/
artifacts:
  files:
    - "build/*"
    - "build/**/*"